return {
	Elite = {
		HPMultiplier = 2.65,
		DamageMultiplier = 1.45,
		CoinMultiplier = 3.0,
		XPMultiplier = 2.4,
		Scale = 1.14,
		Names = {
			[1] = "Dojo Enforcer",
			[2] = "Cinder Champion",
			[3] = "Citadel Warden",
			[4] = "Abyss Herald",
		},
	},

	MasteryPerks = {
		{Threshold = 50, Name = "Adept", DamageBonus = 0.02, Description = "+2% total style damage"},
		{Threshold = 150, Name = "Finisher", DamageBonus = 0.03, Description = "+3% total style damage"},
		{Threshold = 300, Name = "Resonance", DamageBonus = 0.04, Description = "+4% total style damage"},
		{Threshold = 500, Name = "Ascended Style", DamageBonus = 0.06, Description = "+6% total style damage"},
	},

	RegionQuestChains = {
		[1] = {
			Region = "Verdant Wilds",
			{
				Title = "Rogues on the Road",
				Type = "Kills",
				Target = 5,
				Description = "Defeat 5 Dojo Rogues around the Verdant roads.",
				Coins = 180,
				Gems = 0,
				XP = 90,
			},
			{
				Title = "Break the Camp",
				Type = "Elites",
				Target = 1,
				Description = "Defeat the Dojo Enforcer.",
				Coins = 420,
				Gems = 2,
				XP = 180,
			},
			{
				Title = "Verdant Trial",
				Type = "Kills",
				Target = 12,
				Description = "Clear 12 more Verdant enemies and prove the route safe.",
				Coins = 850,
				Gems = 4,
				XP = 360,
			},
		},
		[2] = {
			Region = "Ember Ravine",
			{
				Title = "Ashen Patrol",
				Type = "Kills",
				Target = 8,
				Description = "Defeat 8 Ember Ronin across the ravine.",
				Coins = 950,
				Gems = 2,
				XP = 420,
			},
			{
				Title = "Champion of Cinders",
				Type = "Elites",
				Target = 2,
				Description = "Defeat 2 Cinder Champions.",
				Coins = 1800,
				Gems = 4,
				XP = 720,
			},
			{
				Title = "Forgebreaker",
				Type = "Kills",
				Target = 16,
				Description = "Push through 16 Ember enemies around the forge quarter.",
				Coins = 3200,
				Gems = 7,
				XP = 1150,
			},
		},
		[3] = {
			Region = "Frost Highlands",
			{
				Title = "Cold Front",
				Type = "Kills",
				Target = 10,
				Description = "Defeat 10 Frost Wardens along Frostfall Pass.",
				Coins = 2600,
				Gems = 4,
				XP = 1050,
			},
			{
				Title = "Citadel Hunters",
				Type = "Elites",
				Target = 2,
				Description = "Defeat 2 Citadel Wardens.",
				Coins = 4300,
				Gems = 7,
				XP = 1700,
			},
			{
				Title = "Whiteout",
				Type = "Kills",
				Target = 18,
				Description = "Break the remaining Frost patrols.",
				Coins = 6800,
				Gems = 10,
				XP = 2600,
			},
		},
		[4] = {
			Region = "Void Scar",
			{
				Title = "Into the Scar",
				Type = "Kills",
				Target = 12,
				Description = "Defeat 12 Void Reapers beyond the ruined arch.",
				Coins = 7200,
				Gems = 8,
				XP = 2500,
			},
			{
				Title = "Heralds of the Abyss",
				Type = "Elites",
				Target = 3,
				Description = "Defeat 3 Abyss Heralds.",
				Coins = 12500,
				Gems = 13,
				XP = 4200,
			},
			{
				Title = "Break the Tyrant",
				Type = "Boss",
				Target = 1,
				Description = "Defeat the Rift Tyrant at the end of the Void ascent.",
				Coins = 25000,
				Gems = 25,
				XP = 8000,
			},
		},
	},
}
