return {
	RareChance = {
		[1] = 0.050,
		[2] = 0.055,
		[3] = 0.060,
		[4] = 0.070,
	},

	Rares = {
		[1] = {
			Id = "FallenDisciple",
			Name = "Kaien, the Fallen Disciple",
			Hint = "A fallen swordsman has been sighted near the Verdant roads.",
			HPMultiplier = 4.0,
			DamageMultiplier = 1.55,
			CoinMultiplier = 7.0,
			XPMultiplier = 5.0,
			Gems = {1, 3},
			Scale = 1.18,
			BonusRelicChance = 0.35,
		},
		[2] = {
			Id = "Cinderblade",
			Name = "Varka, the Cinderblade",
			Hint = "An infamous duelist is roaming the Ember Ravine.",
			HPMultiplier = 4.4,
			DamageMultiplier = 1.60,
			CoinMultiplier = 7.5,
			XPMultiplier = 5.4,
			Gems = {2, 4},
			Scale = 1.20,
			BonusRelicChance = 0.40,
		},
		[3] = {
			Id = "PaleSentinel",
			Name = "Eira, the Pale Sentinel",
			Hint = "A silent sentinel is hunting travelers in the Frost Highlands.",
			HPMultiplier = 4.8,
			DamageMultiplier = 1.66,
			CoinMultiplier = 8.0,
			XPMultiplier = 5.8,
			Gems = {3, 6},
			Scale = 1.22,
			BonusRelicChance = 0.45,
		},
		[4] = {
			Id = "RiftStalker",
			Name = "Nyxar, the Rift Stalker",
			Hint = "Something powerful is stalking the broken paths of the Void Scar.",
			HPMultiplier = 5.2,
			DamageMultiplier = 1.72,
			CoinMultiplier = 9.0,
			XPMultiplier = 6.3,
			Gems = {5, 9},
			Scale = 1.25,
			BonusRelicChance = 0.55,
		},
	},

	NPCs = {
		{
			Id = "AsterVale",
			Name = "Aster Vale",
			Title = "Rift Warden",
			ZoneId = 0,
			Position = Vector3.new(0, 5, -38),
			Color = Color3.fromRGB(111, 103, 88),
			Intro = {
				"Rift Haven is the last quiet place before the roads split into dangerous territory.",
				"Follow the regional wardens. They know what is changing beyond the walls.",
			},
		},
		{
			Id = "MiraThorn",
			Name = "Mira Thorn",
			Title = "Verdant Scout",
			ZoneId = 1,
			Position = Vector3.new(-16, 5, 126),
			Color = Color3.fromRGB(76, 112, 72),
			Intro = {"The road looks peaceful from Haven. It isn't.", "Rogues are using the forest paths to move unseen."},
		},
		{
			Id = "TorrenAsh",
			Name = "Torren Ash",
			Title = "Ravine Smith",
			ZoneId = 2,
			Position = Vector3.new(150, 5, 82),
			Color = Color3.fromRGB(142, 77, 51),
			Intro = {"The forge fires have been burning without a smith at the bellows.", "The Ronin have claimed the old quarter."},
		},
		{
			Id = "IlyraFenn",
			Name = "Ilyra Fenn",
			Title = "Highland Pathfinder",
			ZoneId = 3,
			Position = Vector3.new(34, 5, -150),
			Color = Color3.fromRGB(105, 139, 158),
			Intro = {"Snow hides tracks, not intent.", "The Wardens are gathering around the old citadel again."},
		},
		{
			Id = "VeylOrin",
			Name = "Veyl Orin",
			Title = "Rift Scholar",
			ZoneId = 4,
			Position = Vector3.new(-148, 5, -37),
			Color = Color3.fromRGB(91, 77, 109),
			Intro = {"The Scar is not empty. It watches.", "If the Heralds gather, the Tyrant will not remain dormant."},
		},
	},
}
